### ISSUE TITLE
Cambiar nombre de las secciones de Process Console

### ISSUE THREAD

**Issue by elisvelasquez** [processsuite/ProcessAngular#13]
Cambiar las siguientes etiquetas
  Console por Configurar  o Configuración de
     Configuracion  por Plataforma
     Correo  por Envio de Correo
     Inspeccion por Traza
     Fuente de datos por Base de datos
     Repositorio Fisico por Repositorio
     Administrador por Diseñador 

En el texto de UBICACION (donde se muestra la opcion seleccionada), quitar la palabra BPM y mas bien debe aparecer la concatenacion de CONFIGURAR  o CONFIGURACION DE .... (plataforma, Traza, Base de datos, etc)

**Comment by processsuite** [comment]
Se elimina issue porque esta relacionado a la tarea #16  y el commit se realizo en la tarea #15 por error
